spring:
  datasource:
    url: jdbc:h2:file:~/.h2/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: p@ssw0rd
  h2:
    console:
      enabled: true
      path: /h2-console
